### ISSUE TITLE
Implement clouds moving when game not paused

### ISSUE THREAD

**Issue by WSUCEG7140** [WSUCEG-7140/Tempus_Fugit_Minecraft#4]
https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/1

**Comment by bakursait2** [comment]
**This issue is duplicated**. I am currently working on it but in [issue#21](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/21)

**Comment by bakursait2** [comment]
This issue is duplicated with [issue#21](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/21).
I will close [issue#21](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/21) and work on this one.

**Comment by bakursait2** [comment]
This issue is duplicated with [issue#21](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/21) and [issue#66](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/66).
I will close this [issue#4](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/4) and [issue#21](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/21) and work on [issue#66](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/66).
